import { addMonths, day, today, type Data } from './finance';
export function sampleData(asOf = today()): Data {
  const relative = (days: number) => {
    const d = day(asOf);
    d.setUTCDate(d.getUTCDate() + days);
    return d.toISOString().slice(0, 10);
  };
  return {
    settings: {
      name: 'Balaji',
      salaryDay: 10,
      monthlyIncome: 5500000,
      essentialReserve: 600000,
      emergencyReserve: 500000,
      goalReserve: 250000,
      extraDebtReserve: 0,
    },
    accounts: [
      {
        id: 'bank-1',
        name: 'HDFC · Salary account',
        kind: 'BANK',
        balance: 4285000,
        spendable: true,
      },
      {
        id: 'bank-2',
        name: 'Long-term savings',
        kind: 'SAVINGS',
        balance: 6500000,
        spendable: false,
      },
    ],
    incomes: [
      {
        id: 'income-1',
        amount: 5500000,
        date:
          day(asOf).getUTCDate() < 10
            ? addMonths(asOf, -1, 10).toISOString().slice(0, 10)
            : asOf.slice(0, 8) + '10',
        source: 'Salary',
        status: 'RECEIVED',
        recurring: true,
        notes: 'Editable sample salary',
        accountId: 'bank-1',
      },
    ],
    commitments: [
      {
        id: 'c-1',
        name: 'Family support',
        category: 'Family Support',
        amount: 1200000,
        intervalMonths: 1,
        dueDate: relative(22),
        anchorDay: day(relative(22)).getUTCDate(),
        funded: 0,
        paid: 0,
        essential: true,
        active: true,
      },
      {
        id: 'c-2',
        name: 'LIC premium',
        category: 'LIC',
        amount: 934900,
        intervalMonths: 3,
        dueDate: relative(8),
        anchorDay: day(relative(8)).getUTCDate(),
        funded: 600000,
        paid: 0,
        essential: true,
        active: true,
      },
      {
        id: 'c-3',
        name: 'Tuition fee',
        category: 'Tuition',
        amount: 350000,
        intervalMonths: 1,
        dueDate: relative(12),
        anchorDay: day(relative(12)).getUTCDate(),
        funded: 0,
        paid: 0,
        essential: true,
        active: true,
      },
      {
        id: 'c-4',
        name: 'Term insurance',
        category: 'Term Insurance',
        amount: 2547900,
        intervalMonths: 12,
        dueDate: relative(180),
        anchorDay: day(relative(180)).getUTCDate(),
        funded: 1900000,
        paid: 0,
        essential: true,
        active: true,
      },
    ],
    cards: [
      {
        id: 'card-1',
        bank: 'SBI',
        name: 'SBI SimplyCLICK',
        lastFour: '4821',
        creditLimit: 15000000,
        availableLimit: 10320000,
        outstanding: 4680000,
        statementAmount: 2250000,
        statementPaid: 1000000,
        statementDate: relative(-15),
        dueDate: relative(2),
        minimumDue: 125000,
        interestBps: 4200,
        status: 'ACTIVE',
        emis: [],
      },
      {
        id: 'card-2',
        bank: 'Axis Bank',
        name: 'Axis Neo',
        lastFour: '9016',
        creditLimit: 10000000,
        availableLimit: 6950000,
        outstanding: 3050000,
        statementAmount: 1400000,
        statementPaid: 1400000,
        statementDate: relative(-20),
        dueDate: relative(6),
        minimumDue: 70000,
        interestBps: 4200,
        status: 'FROZEN',
        emis: [],
      },
      {
        id: 'card-3',
        bank: 'HDFC',
        name: 'HDFC Millennia',
        lastFour: '3372',
        creditLimit: 20000000,
        availableLimit: 15500000,
        outstanding: 2100000,
        statementAmount: 0,
        statementPaid: 0,
        statementDate: relative(-4),
        dueDate: relative(18),
        minimumDue: 0,
        interestBps: 3600,
        status: 'ACTIVE',
        emis: [
          {
            id: 'emi-1',
            cardId: 'card-3',
            name: 'Laptop EMI',
            originalAmount: 4800000,
            principalRemaining: 2400000,
            monthlyEmi: 420000,
            nextPrincipal: 400000,
            nextInterest: 20000,
            totalInstallments: 12,
            installmentsPaid: 6,
            nextDate: relative(20),
            anchorDay: day(relative(20)).getUTCDate(),
          },
        ],
      },
    ],
    expenses: [
      {
        id: 'e-1',
        amount: 245000,
        date: relative(-1),
        category: 'Groceries',
        method: 'UPI',
        description: 'Weekly groceries',
        essentiality: 'MUST HAVE',
        accountId: 'bank-1',
        cardId: null,
      },
      {
        id: 'e-2',
        amount: 85000,
        date: relative(-2),
        category: 'Eating Out',
        method: 'Credit Card',
        description: 'Dinner with friends',
        essentiality: 'WANT',
        accountId: null,
        cardId: 'card-1',
      },
      {
        id: 'e-3',
        amount: 180000,
        date: relative(-3),
        category: 'Fuel',
        method: 'UPI',
        description: 'Petrol',
        essentiality: 'MUST HAVE',
        accountId: 'bank-1',
        cardId: null,
      },
      {
        id: 'e-4',
        amount: 320000,
        date: relative(-4),
        category: 'Shopping',
        method: 'Credit Card',
        description: 'Weekend shopping',
        essentiality: 'WANT',
        accountId: null,
        cardId: 'card-1',
      },
      {
        id: 'e-5',
        amount: 29900,
        date: relative(-5),
        category: 'Mobile Recharge',
        method: 'UPI',
        description: 'Monthly recharge',
        essentiality: 'MUST HAVE',
        accountId: 'bank-1',
        cardId: null,
      },
    ],
    payments: [
      {
        id: 'p-1',
        amount: 1000000,
        date: relative(-3),
        type: 'STATEMENT',
        accountId: 'bank-1',
        cardId: 'card-1',
        commitmentId: null,
        notes: 'Partial statement payment',
      },
      {
        id: 'p-2',
        amount: 1400000,
        date: relative(-5),
        type: 'STATEMENT',
        accountId: 'bank-1',
        cardId: 'card-2',
        commitmentId: null,
        notes: 'Statement settled',
      },
    ],
  };
}
