ALTER TABLE "Card" ADD COLUMN "detailsComplete" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Card" ADD COLUMN "notes" TEXT;
ALTER TABLE "Income" ADD COLUMN "balanceApplied" BOOLEAN NOT NULL DEFAULT true;
